name: e2e-test
on:
  # Runs every day at 3:12 UTC.
  # schedule:
  #   - cron: '12 3 * * *'
  # Allow manually triggered runs.
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-e2e-aws-oidc:
    runs-on: ubuntu-latest
    # Makes it so only one instance of this workflow can run at a time:
    # https://docs.github.com/en/actions/using-jobs/using-concurrency
    concurrency: run-e2e-aws-oidc
    env:
      # Arguments for running the aws-nuke docker container.
      #
      # --config: GitHub runs docker container steps with $GITHUB_WORKSPACE bound to /github/workspace in the container.
      # --no-dry-run: Actually delete resources.
      # --force, --force-sleep: Disable interactive mode.
      NUKE_ARGS: --config /github/workspace/cloud-deploy-infra/e2e-test/nuke.yaml --no-dry-run --force --force-sleep=3 
    steps:
      - name: Checkout avritt/cloud-deploy-infra
        uses: actions/checkout@v3
        with:
          repository: avrittrohwer/cloud-deploy-infra
          path: cloud-deploy-infra

      - name: Checkout civiform/civiform-deploy
        uses: actions/checkout@v3
        with:
          repository: civiform/civiform-deploy
          path: civiform-deploy

      - id: get-aws-creds
        name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # Role in avritt-dev account.
          role-to-assume: arn:aws:iam::096708045127:role/e2e-test-runner
          aws-region: us-east-1

      - id: pre-nuke
        name: Pre nuke
        uses: docker://rebuy/aws-nuke:v2.21.2
        with:
          args: ${{env.NUKE_ARGS}}

      - name: Run bin/setup
        run: |
          # Must run setup scripts from this directory due to 'source' lines in the scripts.
          # cd $GITHUB_WORKSPACE/civiform-deploy
          # yes yes | bin/setup --config=$GITHUB_WORKSPACE/cloud-deploy-infra/e2e-test/civiform_config_aws_oidc.sh
          echo 'Ran bin/setup'

      - name: Post nuke
        # Post nuke should run even if bin/setup fails. Therefore we need the
        # '(success() || failure())' condition: if a status check function is
        # not included in the 'if', the success() function is included by
        # default:
        # https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions.
        if: (success() || failure()) && steps.get-aws-creds.outcome == 'success' && steps.pre-nuke.outcome == 'success'
        uses: docker://rebuy/aws-nuke:v2.21.2
        with:
          args: ${{env.NUKE_ARGS}}
